export const regCodes={
    AE: 'United Arab Emirates',
    AR: 'Argentina',
    AT: 'Austria',
    AU: 'Australia',
    BG: 'Bulgaria',
    BH: 'Bahrain',
    BM: 'Bermuda',
    BO: 'Bolivia',
    BR: 'Brazil',
    CA: 'Canada',
    CH: 'Switzerland',
    CL: 'Chile',
    CN: 'China',
    CO: 'Colombia',
    CR: 'Costa Rica',
    CS: 'Serbia and Montenegro',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    DE: 'Germany',
    DK: 'Denmark',
    DO: 'Dominican Republic',
    DZ: 'Algeria',
    EC: 'Ecuador',
    EE: 'Estonia',
    EG: 'Egypt',
    ES: 'Spain',
    FI: 'Finland',
    FR: 'France',
    GB: 'United Kingdom',
    GR: 'Greece',
    GT: 'Guatemala',
    HK: 'Hong Kong',
    HN: 'Honduras',
    ID: 'Indonesia',
    IE: 'Ireland',
    IL: 'Israel',
    IN: 'India',
    IS: 'Iceland',
    IT: 'Italy',
    JM: 'Jamaica',
    JO: 'Jordan',
    JP: 'Japan',
    KE: 'Kenya',
    KR: 'Republic of Korea (South Korea)',
    KW: 'Kuwait',
    LB: 'Lebanon',
    LI: 'Liechtenstein',
    LK: 'Sri Lanka',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MA: 'Morocco',
    MU: 'Mauritius',
    MX: 'Mexico',
    NL: 'Netherlands',
    NO: 'Norway',
    NZ: 'New Zealand',
    OM: 'Oman',
    PA: 'Panama',
    PE: 'Peru',
    PH: 'Philippines',
    PK: 'Islamic Republic of Pakistan',
    PL: 'Poland',
    PR: 'Puerto Rico',
    PT: 'Portugal',
    QA: 'Qatar',
    RO: 'Romania',
    RU: 'Russia',
    SA: 'Saudi Arabia',
    SG: 'Singapore',
    SI: 'Slovenia',
    SK: 'Slovak Republic',
    SV: 'El Salvador',
    TH: 'Thailand',
    TN: 'Tunisia',
    TR: 'Turkey',
    TT: 'Trinidad and Tobago',
    TW: 'Taiwan',
    UA: 'Ukraine',
    US: 'United States',
    UY: 'Uruguay',
    VE: 'Venezuela',
    VN: 'Vietnam',
    ZA: 'South Africa',
    getRegion : function(sCode){ return this[sCode]},
    toJSON : function() {
        let s="".concat("[");
        let keys = Object.keys(this);
        let values = Object.values(this);
        for (var key in keys){ 
            if (keys[key].length==2){
                s=s.concat(
                    "{\"ID\":",key,",\n",
                    "\"Code\":\"",keys[key],"\",\n",
                    "\"Region\":\"",this[keys[key]],"\"\n",
                    "},\n"
                );
            }   
        }
        if (s.length>0) s=s.slice(0,s.length-2); // remove last ,n 
        s=s.concat("\n]");
        return s;
    }
}